# This sends a sequence of actions to the step action server.
# This service call is will only block until the action has been
# successfully started or failed during initialization.
# If you need feedback about the progress or successful
# execution of the action (outside of the action itself), use
# the `ExecuteActionSequence` ROS action.

free_gait_msgs/ExecuteActionGoal[] goals
---
free_gait_msgs/ExecuteActionResult result
